

reftrg: 
		gfortran reftrg.f -o reftrg /usr/local/sac/lib/sacio.a

reftrg2: 
		gfortran reftrg2.f -o reftrg2 /usr/local/sac/lib/sacio.a

nettrg:	 
		gfortran nettrg.f -mcmodel=medium -o nettrg

nettrg2:	 
		gfortran nettrg2.f -mcmodel=medium -o nettrg2

reftrgOrg:	
		gfortran reftrgOrg.f -o reftrgOrg /usr/local/sac/lib/sacio.a




